<?php

namespace App\Filament\Resources;

use App\Filament\Resources\StockMovementResource\Pages;
use App\Filament\Resources\StockMovementResource\RelationManagers;
use App\Filament\Resources\StockMovementResource\Widgets\StatsMovOverview;
use App\Models\StockMovement;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Forms\Components\Select;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class StockMovementResource extends Resource
{
    protected static ?string $model = StockMovement::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('cantidad_movimiento')
                ->autofocus()
                ->required()
                ->placeholder(__('Cantidad')),
                Select::make('stock_id')
                ->relationship('stock', 'nombre')
                ->required()
                ->searchable(),
                Select::make('persona')
                ->options([

'ACOSTA RICHARD' =>'ACOSTA RICHARD',
'ACOSTA ORLANDO' =>  'ACOSTA ORLANDO',
'ACOSTAANGEL'=> 'ACOSTAANGEL' ,
'ACOSTAHUGO'=> 'ACOSTAHUGO' ,
'ACOSTAMANUEL' => 'ACOSTAMANUEL',
'ACOSTAMATIAS' => 'ACOSTAMATIAS',
'ACUÑACRISTIAN' => 'ACUÑACRISTIAN',
'AGUERO JUAN OSVALDO' => 'AGUERO JUAN OSVALDO',
'AGUEROCLAUDIO' => 'AGUEROCLAUDIO',
'AGUIRREOMAR' => 'AGUIRREOMAR',
'AGUIRRE MARTIN' => 'AGUIRRE MARTIN',
'AIRBAR RODRIGOALEJANDRO ' => 'AIRBAR RODRIGOALEJANDRO ',
'ALARCON JORGE RUBEN' => 'ALARCON JORGE RUBEN',
'ALARCONHECTOR' => 'ALARCONHECTOR',
'ALFARO CARLOS DANIEL' => 'ALFARO CARLOS DANIEL',
'ALDERETE IVANA' => 'ALDERETE IVANA',
'AMANI AGUSTIN' => 'AMANI AGUSTIN',
'ANAVIA ROQUE' => 'ANAVIA ROQUE',
'ANTELO RAMON' => 'ANTELO RAMON',
'APAZA  JORGE ENMANUEL' => 'APAZA  JORGE ENMANUEL',
'AYBAR RODRIGO' => 'AYBAR RODRIGO',
'APAZAHECTOR' =>    'APAZAHECTOR',
'APAZAJORGE' => 'APAZAJORGE',
'APAZAJORGE DANIEL' => 'APAZAJORGE DANIEL',
'APAZAPEDRO' => 'APAZAPEDRO',
'APAZASERGIO DANIEL' => 'APAZASERGIO DANIEL',
'APUD MIGUEL ANGEL' => 'APUD MIGUEL ANGEL',
'ARANCIBIA JHONATAN' => 'ARANCIBIA JHONATAN',
'ARAPAMARCELO' => 'ARAPAMARCELO',
'ARIAS LEONARDO' => 'ARIAS LEONARDO',
'ARMELLA NESTOR' => 'ARMELLA NESTOR',
'ARREDONDO CLAUDIO' => 'ARREDONDO CLAUDIO',
'ARROYOALBERTO MARTIN' => 'ARROYOALBERTO MARTIN',
'ASTORGA MARIO' =>  'ASTORGA MARIO',
'ASTORGA JAVIER' => 'ASTORGA JAVIER',
'AVILAJORGE DARIO' => 'AVILAJORGE DARIO',
'AYBAR GUSTAVO' => 'AYBAR GUSTAVO',
'BANEGAS REYNALDO GUSTAVO' => 'BANEGAS REYNALDO GUSTAVO',
'BARRIENTOS LEONEL' => 'BARRIENTOS LEONEL',
'BEJARANO EMILIO' => 'BEJARANO EMILIO',
'BERMUDEZ CARLOS' => 'BERMUDEZ CARLOS',
'BERMUDEZPABLO' => 'BERMUDEZPABLO',
'BRIZUELA SEBASTIAN' => 'BRIZUELA SEBASTIAN',
'BRUNO VICTOR' => 'BRUNO VICTOR',
'BURGOS ESTEBAN' => 'BURGOS ESTEBAN',
'BURGOS ELVIO' => 'BURGOS ELVIO',
'BUSTAMANTE JOSE' =>    'BUSTAMANTE JOSE',
'CABANA ALEXANDER' => 'CABANA ALEXANDER',
'CABRERA MARTIN' => 'CABRERA MARTIN',
'CAMPOS HECTOR' => 'CAMPOS HECTOR',
'CAMPOS ROBERTO' =>     'CAMPOS ROBERTO',
'CANCHI RICARDO' => 'CANCHI RICARDO',
'CANCH SIXTO' => 'CANCH SIXTO',
'CARDONA GONZALO' => 'CARDONA GONZALO',
'CARDOZO ELIAS' => 'CARDOZO ELIAS',
'CARDOZO SILVIO' =>     'CARDOZO SILVIO',
'CARDOZO LUIS' => 'CARDOZO LUIS',
'CARDOZO JOSE JESUS' => 'CARDOZO JOSE JESUS',
'CARDOZO RAFAEL' =>     'CARDOZO RAFAEL',
'CARDOZOLUIS ROBERTO' => 'CARDOZOLUIS ROBERTO',
'CARI DAVID ALBERTO' => 'CARI DAVID ALBERTO',
'CARI DIEGO' => 'CARI DIEGO',
'CASASOLA VICTOR' => 'CASASOLA VICTOR',
'CASASOLA ISMAEL' =>    'CASASOLA ISMAEL',
'CASTAÑO JOSE' => 'CASTAÑO JOSE',
'CASTANO DANIEL' => 'CASTANO DANIEL',
'CASTILLO FRANCO' => 'CASTILLO FRANCO',
'CASTILLO SANTIAGO' =>  'CASTILLO SANTIAGO',
'CASTILLODARIO' => 'CASTILLODARIO',
'CASTILLOFRANCO' => 'CASTILLOFRANCO',
'CAUCOTA NESTOR' => 'CAUCOTA NESTOR',
'CAUCOTAROLDOLFO' => 'CAUCOTAROLDOLFO',
'CEJAS LUCIANO' => 'CEJAS LUCIANO',
'CHACHAGUA ANTONIO' => 'CHACHAGUA ANTONIO',
'CHACHAGUA RAMON' => 'CHACHAGUA RAMON',
'CHACONAMERICANO' => 'CHACONAMERICANO',
'CHAPARRO JUAN CARLOS' => 'CHAPARRO JUAN CARLOS',
'CHAPARRO RUBEN' => 'CHAPARRO RUBEN',
'CHOCOBAR CARLOS MIGUEL' => 'CHOCOBAR CARLOS MIGUEL',
'CHOQUEAVEL' => 'CHOQUEAVEL',
'CHUMBITA JESUS' => 'CHUMBITA JESUS',
'CISNERO MIGUEL' => 'CISNERO MIGUEL',
'COLCHIHERNAN' => 'COLCHIHERNAN',
'CORBOHUGO' =>  'CORBOHUGO',
'CORDOBA EDUARDO' => 'CORDOBA EDUARDO',
'CORNEJOANTONIO' => 'CORNEJOANTONIO',
'CORONEL MAXIMILIANO' => 'CORONEL MAXIMILIANO',
'CORREGIDORMATIAS' => 'CORREGIDORMATIAS',
'CORTEZ ARIEL ROBERTO' => 'CORTEZ ARIEL ROBERTO',
'COSTILLA GONZALO MATIAS' => 'COSTILLA GONZALO MATIAS',
'COSTILLACARLOS' => 'COSTILLACARLOS',
'COSTILLA SANTIAGO' => 'COSTILLA SANTIAGO',
'COPA MARIO' => 'COPA MARIO',
'CRUZ ALEJANDRO' =>     'CRUZ ALEJANDRO',
'CRUZ DOMINGO' => 'CRUZ DOMINGO',
'CRUZADOLFO' => 'CRUZADOLFO',
'CRUZALBERTO DAVID' => 'CRUZALBERTO DAVID',
'CRUZ VICTOR' => 'CRUZ VICTOR',
'CRUZSANTIAGO PEDRO' => 'CRUZSANTIAGO PEDRO',
'CRUZ OSWALDO' => 'CRUZ OSWALDO',
'CRUZ CASTILLO HERMINIO' => 'CRUZ CASTILLO HERMINIO',
'DIAZ MIGUEL ANGEL' => 'DIAZ MIGUEL ANGEL',
'DORADO ADRIAN RAMIRO' => 'DORADO ADRIAN RAMIRO',
'DOMINGUEZ HECTOR ANDRES' => 'DOMINGUEZ HECTOR ANDRES',
'DORADO LAUTARO EXEQUIEL' => 'DORADO LAUTARO EXEQUIEL',
'ESCUDERO JUAN ANTONIO' => 'ESCUDERO JUAN ANTONIO',
'ESPINOZA ANDRES' => 'ESPINOZA ANDRES',
'ESPINOZA JOSE' => 'ESPINOZA JOSE',
'FARFAN ISMAEL' => 'FARFAN ISMAEL',
'FERNANDEZ ANIBAL' => 'FERNANDEZ ANIBAL',
'FERNANDEZ OMAR SANJIM' => 'FERNANDEZ OMAR SANJIM',
'FERNÁNDEZ JOEL' => 'FERNÁNDEZ JOEL',
'FERNANDEZ ENMANUEL' => 'FERNANDEZ ENMANUEL',
'FERNANDEZ FEDERICO' => 'FERNANDEZ FEDERICO',
'FERNANDEZ CRISTIAN' => 'FERNANDEZ CRISTIAN',
'FERNANDEZJUAN MARCELO' =>  'FERNANDEZJUAN MARCELO',
'FIGUEROA FERNANDO' => 'FIGUEROA FERNANDO',
'FIGUEROA IVAN' => 'FIGUEROA IVAN',
'FLORES ALDO' => 'FLORES ALDO',
'FLORES CARLOS VICTOR DAMIAN' =>    'FLORES CARLOS VICTOR DAMIAN',
'FLORESNESTOR' => 'FLORESNESTOR',
'FRETES NELSON' =>  'FRETES NELSON',
'GARCIAALVARO' => 'GARCIAALVARO',
'GARZON CASTILLO MATIAS GABRIEL' => 'GARZON CASTILLO MATIAS GABRIEL',
'GOMEZ CRISTIAN' => 'GOMEZ CRISTIAN',
'GONZAMAURICIO' =>  'GONZAMAURICIO',
'GONZALEZ  CARLOS' => 'GONZALEZ  CARLOS',
'GONZALEZ  FEDERICO' => 'GONZALEZ  FEDERICO',
'GONZALEZ MARIANA' => 'GONZALEZ MARIANA',
'GUANTAY FABIO' => 'GUANTAY FABIO',
'GUAYMAS SERGIO' => 'GUAYMAS SERGIO',
'GUERRA  DANTE' => 'GUERRA  DANTE',
'GUITERREZ GREGORIO' => 'GUITERREZ GREGORIO',
'GUTIERREZ MARCELO' => 'GUTIERREZ MARCELO',
'GUTIERREZ PABLO' => 'GUTIERREZ PABLO',
'GUZMAN RAMIRO' => 'GUZMAN RAMIRO',
'HERRERA CASTILLO' => 'HERRERA CASTILLO',
'HUMACATADIEGO' => 'HUMACATADIEGO',
'IFRANLAZARO' => 'IFRANLAZARO',
'IBAÑEZ SERGIO' => 'IBAÑEZ SERGIO',
'INSUAPABLO' => 'INSUAPABLO',
'JARPAMIGUEL' => 'JARPAMIGUEL',
'JASSE ANGEL ANGEL' => 'JASSE ANGEL ANGEL',
'JURADOWILFREDO' => 'JURADOWILFREDO',
'JUSTINIANO LUCAS' => 'JUSTINIANO LUCAS',
'LIZANDRO FACUNDO' => 'LIZANDRO FACUNDO',
'LEON FRANCISCO' => 'LEON FRANCISCO',
'LOPEZ  MIGUEL ENRIQUE' => 'LOPEZ  MIGUEL ENRIQUE',
'LOPEZ CESAR ' => 'LOPEZ CESAR ',
'LOPEZ CAIN ALEJANDRO' => 'LOPEZ CAIN ALEJANDRO',
'LOPEZ MILTON CESAR' => 'LOPEZ MILTON CESAR',
'LOPEZ YANINA' => 'LOPEZ YANINA',
'LOPEZDANIEL' => 'LOPEZDANIEL',
'LOPEZJOSE' => 'LOPEZJOSE',
'LOPEZPAVEL RENZO' =>   'LOPEZPAVEL RENZO',
'LUNA  FACUNDO' => 'LUNA  FACUNDO',
'LUNA FABIO' => 'LUNA FABIO',
'LUNA  HUGO' => 'LUNA  HUGO',
'LUNA  JUAN' => 'LUNA  JUAN',
'LEON FRANCISCO' => 'LEON FRANCISCO',
'MADRIGAL  RENE' => 'MADRIGAL  RENE',
'MAMANI  ANGEL' => 'MAMANI  ANGEL',
'MAMANI  GABRIEL' => 'MAMANI  GABRIEL',
'MAMANI  MAURICIO' => 'MAMANI  MAURICIO',
'MAMANI  MIGUEL' => 'MAMANI  MIGUEL',
'MAMANI JUAN CARLOS' => 'MAMANI JUAN CARLOS',
'MAMANI CARLOS' => 'MAMANI CARLOS',
'MANSILLA PABLO' => 'MANSILLA PABLO',
'MARAZ LUIS' => 'MARAZ LUIS',
'MARQUEZ DIEGO' => 'MARQUEZ DIEGO',
'MARQUEZ OMAR' =>   'MARQUEZ OMAR',
'MARTINEZ LUIS' =>      'MARTINEZ LUIS',
'MARZEJOSE' => 'MARZEJOSE',
'MAZA GONZALO JAVIER' =>    'MAZA GONZALO JAVIER',
'MEALLAHECTOR ' => 'MEALLAHECTOR ',
'MEDINA  MANUEL' =>  'MEDINA MANUEL',
'MEDINALUCAS' => 'MEDINALUCAS',
'MEDINAMANUEL' => 'MEDINAMANUEL',
'MENDEZ JORGE LUIS' => 'MENDEZ JORGE LUIS',
'MICHEL FEDERICO' => 'MICHEL FEDERICO',
'MIRANDA DANIEL' => 'MIRANDA DANIEL',
'MIRANDA FACUNDO' => 'MIRANDA FACUNDO',
'MIRANDA MIGUEL' => 'MIRANDA MIGUEL',
'MOLINA JORGUE HUMBERTO' => 'MOLINA JORGUE HUMBERTO',
'MONSERRATHECTOR' => 'MONSERRATHECTOR',
'MONSERRATHECTOR' => 'MONSERRATHECTOR',
'MORALES WALTER JOAQUIN' => 'MORALES WALTER JOAQUIN',
'MORALESALEJANDRO' => 'MORALESALEJANDRO',
'MOYA  MANUEL' => 'MOYA MANUEL',
'MURIENEGA  OMAR' => 'MURIENEGA OMAR',
'NAVARRO  NELSON' => 'NAVARRO NELSON',
'NERISRODOLFO' => 'NERISRODOLFO',
'NIEVA  VICTOR' => 'NIEVA VICTOR',
'NIEVA FACUNDO' => 'NIEVA FACUNDO',
'NOGALEZ NAHUEL' => 'NOGALEZ NAHUEL',
'OLARTE ANGEL FELICIANO' => 'OLARTE ANGEL FELICIANO',
'OLIVARES MARIO ALBERTO' =>     'OLIVARES MARIO ALBERTO',
'OLIVERA  CLAUDIO' => 'OLIVERA  CLAUDIO',
'OLIVERA HUGO FERNANDO' => 'OLIVERA HUGO FERNANDO',
'ORMACHEA  JAVIER' => 'ORMACHEA  JAVIER',
'ORQUERA SEBASTIAN' => 'ORQUERA SEBASTIAN',
'ORTEGA  DANIEL NICOLAS' => 'ORTEGA  DANIEL NICOLAS',
'ORTEGA LUCAS' => 'ORTEGA LUCAS',
'ORTEGAJUAN' => 'ORTEGAJUAN',
'OVEJEROMIGUEL' => 'OVEJEROMIGUEL',
'PACHADO CARLOS ' => 'PACHADO CARLOS ',
'PERDOMO ALICIA' => 'PERDOMO ALICIA',
'PACHECO MAURICIO' => 'PACHECO MAURICIO',
'PACO  MARIO' => 'PACO  MARIO',
'PADILLAADRIAN ANDRES' => 'PADILLAADRIAN ANDRES',
'PADILLAWALTER' => 'PADILLAWALTER',
'PANTOJALORENZO' => 'PANTOJALORENZO',
'PANTOJASANDRO' => 'PANTOJASANDRO',
'PAZ  JUAN GABRIEL' => 'PAZ  JUAN GABRIEL',
'PELOC ALBERTO' => 'PELOC ALBERTO',
'PELOC  PABLO' => 'PELOC  PABLO',
'PELOC AGUSTIN' => 'PELOC AGUSTIN',
'PELOC JOSE ADRIAN' => 'PELOC JOSE ADRIAN',
'PINEDA RAMON' => 'PINEDA RAMON',
'PEREYRA ALDO' => 'PEREYRA ALDO',
'PEREYRA CLAUDIO' => 'PEREYRA CLAUDIO',
'PEREYRASANTIAGO' => 'PEREYRASANTIAGO',
'PEREYRA JAVIER' => 'PEREYRA JAVIER',
'PLAZA CARLOS DANIEL' => 'PLAZA CARLOS DANIEL',
'POCLAVA FELIX' => 'POCLAVA FELIX',
'POCLAVASANTOS' => 'POCLAVASANTOS',
'PUCA ALEJANDRO NICOLAS' => 'PUCA ALEJANDRO NICOLAS',
'QUILPIDORRICARDO' => 'QUILPIDORRICARDO',
'QUIROGA DAVID ALBERTO' =>  'QUIROGA DAVID ALBERTO',
'QUISPE LUCAS' => 'QUISPE LUCAS',
'RAMIRES NELSON' => 'RAMIRES NELSON',
'RAMOS JUAN' => 'RAMOS JUAN',
'RAMOS WALTER' => 'RAMOS WALTER',
'RIOS  DANIEL' => 'RIOS  DANIEL',
'ROBLEDOEDUARDO' => 'ROBLEDOEDUARDO',
'ROCHA LUIS' => 'ROCHA LUIS',
'RODASJONATHAN' => 'RODASJONATHAN',
'RODRIGUEZ WALTER' => 'RODRIGUEZ WALTER',
'RODRIGUEZ FABIO' => 'RODRIGUEZ FABIO',
'RODRIGUEZPABLO JAV' => 'RODRIGUEZPABLO JAV',
'RODRIGUEZRUBEN' => 'RODRIGUEZRUBEN',
'ROJAS JOSE ANTONIO' => 'ROJAS JOSE ANTONIO',
'ROJAS ARAYA DANIEL HIPOLITO' => 'ROJAS ARAYA DANIEL HIPOLITO',
'ROJAS LEONARDO' =>     'ROJAS LEONARDO',
'ROMAN GRACIELA' => 'ROMAN GRACIELA',
'ROMERO JAVIER' => 'ROMERO JAVIER',
'ROMERO LUIS ORLANDO' => 'ROMERO LUIS ORLANDO',
'ROMEROCARLOS' => 'ROMEROCARLOS',
'ROQUEANAVIA' => 'ROQUEANAVIA',
'SAIQUITA  SANTOS' => 'SAIQUITA  SANTOS',
'SAIQUITA MIGUEL' => 'SAIQUITA MIGUEL',
'SAIQUITA JUAN' =>      'SAIQUITA JUAN',
'SALASENMANUEL' => 'SALASENMANUEL',
'SANCHEZ JULIO' => 'SANCHEZ JULIO',
'SANCHEZ RAMON' => 'SANCHEZ RAMON',
'SANMILLA MATIAS' => 'SANMILLA MATIAS',
'SANMILLANMARTIN' =>    'SANMILLANMARTIN',
'SANTILLAN NESTOR' => 'SANTILLAN NESTOR',
'SARAVIA WALTER' => 'SARAVIA WALTER',
'SAYAGO SERGIO' => 'SAYAGO SERGIO',
'SARA PEDRO ' => 'SARA PEDRO ',
'SARAVIA WALTER' => 'SARAVIA WALTER',
'SARMIENTOCRISTIAN' => 'SARMIENTOCRISTIAN',
'SEQUEIRA LAUTARO' => 'SEQUEIRA LAUTARO',
'SERRANO  DANIEL' => 'SERRANO  DANIEL',
'SERRANO KEVIN' =>   'SERRANO KEVIN',
'SINGH VALERIA' =>   'SINGH VALERIA',
'SOLIVELLAJULIETA' => 'SOLIVELLAJULIETA',
'SOLIZ  CRISTIAN' => 'SOLIZ  CRISTIAN',
'SOLIZ MARIO' => 'SOLIZ MARIO',
'SOLIZJUAN' => 'SOLIZJUAN',
'TAPIABRIAN' => 'TAPIABRIAN',
'TARCAYA  MATIAS' => 'TARCAYA  MATIAS',
'TEJADA AUGUSTO' => 'TEJADA AUGUSTO',
'TEJERINA  VALENTIN' => 'TEJERINA  VALENTIN',
'TISERAEDUARDO' => 'TISERAEDUARDO',
'TOLABA  ALVARO' => 'TOLABA  ALVARO',
'TOLEDOJESUS' => 'TOLEDOJESUS',
'TOLEDOOSCAR' => 'TOLEDOOSCAR',
'TORRESWALTER' => 'TORRESWALTER',
'URAZAGASTEMIGIUEL' => 'URAZAGASTEMIGIUEL',
'USANDIBARA LEONARDO SANJIM' => 'USANDIBARA LEONARDO SANJIM',
'URZAGASTE MARIO' => 'URZAGASTE MARIO',
'ULIVARRE MARCELO' => 'ULIVARRE MARCELO',
'VALDEZ ALZOGARAYOMAR' => 'VALDEZ ALZOGARAYOMAR',
'VEDIA ROBERTO MAURICIO' => 'VEDIA ROBERTO MAURICIO',
'VALDEZHORACIO' => 'VALDEZHORACIO',
'VALE GUSTAVO' => 'VALE GUSTAVO',
'VALDIVIEZOMATIAS' => 'VALDIVIEZOMATIAS',
'VALERIANO RENE' => 'VALERIANO RENE',
'VALLEJO JOSE SANJIM' => 'VALLEJO JOSE SANJIM',
'VALLE MATIAS' => 'VALLE MATIAS',
'VARGAS  ELVIO' => 'VARGAS  ELVIO',
'VEGA  IGNACIO' =>  'VEGA  IGNACIO',
'VILCA MARIO' => 'VILCA MARIO',
'VILLA RAMON' => 'VILLA RAMON',
'VILLA MARCELO' => 'VILLA MARCELO',
'VILLANUEVA JAIRO' => 'VILLANUEVA JAIRO',
'VILLA ROLANDO' => 'VILLA ROLANDO',
'VILLAFAÑEJOAQUIN' => 'VILLAFAÑEJOAQUIN',
'VILLAFUERTE VILCA JUAN CARLOS' => 'VILLAFUERTE VILCA JUAN CARLOS',
'VILLAGRAN SEBASTIAN GABRIEL' => 'VILLAGRAN SEBASTIAN GABRIEL',
'VILLALBA MIGUEL ANGEL' => 'VILLALBA MIGUEL ANGEL',
'VILLAROELYAMILA' =>    'VILLAROELYAMILA',
'VILTEDANIEL' => 'VILTEDANIEL',
'YARI FERNANDO AGUSTIN' => 'YARI FERNANDO AGUSTIN',
'ZAMBRANO JUAN' => 'ZAMBRANO JUAN',
'ZAMORACRISTIAN' => 'ZAMORACRISTIAN',
'ZANCHEZ CARLOS'=> 'ZANCHEZ CARLOSs',
                ])->searchable(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('stock.nombre')
                ->searchable()
                ->sortable(),
                Tables\Columns\TextColumn::make('cantidad_movimiento')
                ->searchable()
                ->sortable(),
                Tables\Columns\TextColumn::make('persona')
                ->searchable()
                ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getWidgets(): array
    {
        return [
            StatsMovOverview::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListStockMovements::route('/'),
            'create' => Pages\CreateStockMovement::route('/create'),
            'edit' => Pages\EditStockMovement::route('/{record}/edit'),
        ];
    }
}
